import 'dart:io';

/// Regenerates `lib/cli/agent_guide_text.g.dart` from `docs/cli/agent-guide.md`
/// (issue #283). Run after editing the markdown:
///
///   dart run tool/gen_agent_guide.dart
///
/// The generated file bundles the guide into the CLI binary as a plain Dart
/// string constant (`kAgentGuideMarkdown`) so `timedart guide` can print it
/// with no filesystem access — the installed binary doesn't carry `docs/`.
/// `test/cli_agent_guide_test.dart` fails if the two files go out of sync, so
/// forgetting to re-run this script after editing the guide is caught in CI.
void main() {
  final source = File('docs/cli/agent-guide.md');
  if (!source.existsSync()) {
    stderr.writeln('error: ${source.path} not found.');
    exit(1);
  }
  final markdown = source.readAsStringSync();

  // A raw triple-quoted string is unusable if the markdown itself contains a
  // `'''` sequence (it would terminate the literal early). Guard against that
  // rather than silently emitting broken Dart.
  if (markdown.contains("'''")) {
    stderr.writeln(
      "error: ${source.path} contains a triple-quote (''') sequence, which "
      'cannot be embedded in a raw Dart string literal. Update this generator '
      'to base64-encode the content instead.',
    );
    exit(1);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_agent_guide.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source of truth: docs/cli/agent-guide.md. Edit that file, then')
    ..writeln('// regenerate with `dart run tool/gen_agent_guide.dart`.')
    ..writeln('//')
    ..writeln('// Bundles the agent-usage guide into the CLI binary as a plain')
    ..writeln("// Dart string so `timedart guide` needs no filesystem access —")
    ..writeln("// the installed binary doesn't carry the docs/ tree.")
    ..writeln()
    ..writeln("const String kAgentGuideMarkdown = r'''")
    ..write(markdown)
    ..writeln("''';");

  final dest = File('lib/cli/agent_guide_text.g.dart');
  dest.writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote ${dest.path} (${markdown.length} bytes of markdown).');
}
